auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  chunk_idle_period: 5m
  chunk_block_size: 512ki
  max_chunk_age: 1h

distributor:
  shard_by_all_labels: true

storage_config:
  boltdb:
    directory: /loki/index

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /loki/ruler
  rule_path: /loki/ruler/rules
  alertmanager_url: http://alertmanager:9093
